
-- Creación de tablas con restricciones

-- Tabla CCALC
CREATE TABLE CCALC (

    Cod_Comu VARCHAR2(10) PRIMARY KEY CONSTRAINT
 PK_CCALC_Cod_Comu,
    Nombre VARCHAR2(20) NOT NULL
);

-- Tabla CENTRO_PROD
CREATE TABLE CENTRO_PROD (

    Cod_Centro NUMBER(3) PRIMARY KEY 
CONSTRAINT PK_CENTRO_PROD_Cod_Centro,
    Cod_Comu VARCHAR2(10) NOT NULL 
CONSTRAINT FK_CENTRO_PROD_Cod_Comu
REFERENCES CCALC(Cod_Comu),
    Nombre_Centro VARCHAR2(20) NOT NULL CONSTRAINT UK_CENTRO_PROD_Nombre UNIQUE
);

-- Tabla SUCURSAL

CREATE TABLE SUCURSAL (

    Cod_Sucu NUMBER(3) PRIMARY KEY 
CONSTRAINT PK_SUCURSAL_Cod_Sucu,
    Cod_Comu VARCHAR2(10) NOT NULL 
CONSTRAINT FK_SUCURSAL_Cod_Comu 
REFERENCES CCALC(Cod_Comu),
   
 Nombre_Sucu VARCHAR2(20) NOT NULL
);

-- Tabla SUC_CEN
CREATE TABLE SUC_CEN (

    Cod_Sucu NUMBER(3) NOT NULL 
CONSTRAINT FK_SUC_CEN_Cod_Sucu 
REFERENCES SUCURSAL(Cod_Sucu),
    
Cod_Centro NUMBER(3) NOT NULL 
CONSTRAINT FK_SUC_CEN_Cod_Centro 
REFERENCES CENTRO_PROD(Cod_Centro),
    
CONSTRAINT PK_SUC_CEN PRIMARY KEY (Cod_Sucu, Cod_Centro)
);

-- Tabla EMPLEADOS
CREATE TABLE EMPLEADOS (

   Cod_Emp NUMBER(3) PRIMARY KEY CONSTRAINT PK_EMPLEADOS_Cod_Emp,
    Cod_Sucu NUMBER(3) NOT NULL 
CONSTRAINT FK_EMPLEADOS_Cod_Sucu 
REFERENCES SUCURSAL(Cod_Sucu),
   
Nombre_Emp VARCHAR2(40) NOT NULL,
    Sueldo NUMBER(10)
 CONSTRAINT CK_EMPLEADOS_Sueldo 
CHECK (Sueldo BETWEEN 14500 AND 60000),
    Comision NUMBER(10) -- Restricción eliminada según solicitud
);

-- Tabla COMPONENTES_Q
CREATE TABLE COMPONENTES_Q (

    Cod_Comp NUMBER(3) PRIMARY KEY 
CONSTRAINT PK_COMPONENTES_Q_Cod_Comp,
    Nombre_Comp VARCHAR2(20) NOT NULL
);

-- Tabla GRUPO
CREATE TABLE GRUPO (

    Cod_Grupo NUMBER(3) PRIMARY KEY 
CONSTRAINT PK_GRUPO_Cod_Grupo,
    Info_Grupo VARCHAR2(20) NOT NULL
);

-- Tabla MEDICAMENTOS
CREATE TABLE MEDICAMENTOS (

    Cod_Medi NUMBER(3) PRIMARY KEY 
CONSTRAINT PK_MEDICAMENTOS_Cod_Medi,
   
 Cod_Centro NUMBER(3) NOT NULL 
CONSTRAINT FK_MEDICAMENTOS_Cod_Centro REFERENCES CENTRO_PROD(Cod_Centro),
    
Cod_Grupo NUMBER(3) NOT NULL CONSTRAINT
 FK_MEDICAMENTOS_Cod_Grupo 
REFERENCES GRUPO(Cod_Grupo),
   
 Tipo_Medi VARCHAR2(20) DEFAULT 'venta' NOT NULL 
CONSTRAINT CK_MEDICAMENTOS_Tipo_Medi 
        CHECK (LOWER(Tipo_Medi) IN ('investigacion', 'venta')),
    Nombre_Medi VARCHAR2(20) NOT NULL
);

-- Tabla MED_COMP
CREATE TABLE MED_COMP (

    Cod_Medi NUMBER(3) NOT NULL CONSTRAINT FK_MED_COMP_Cod_Medi REFERENCES MEDICAMENTOS(Cod_Medi),
    Cod_Comp NUMBER(3) NOT NULL CONSTRAINT FK_MED_COMP_Cod_Comp REFERENCES COMPONENTES_Q(Cod_Comp),
    Cantidad NUMBER(5) CHECK (Cantidad > 0),
    CONSTRAINT PK_MED_COMP PRIMARY KEY (Cod_Medi, Cod_Comp)
);

-- Tabla MED_VENTA
CREATE TABLE MED_VENTA (

    Cod_Medi NUMBER(3) NOT NULL CONSTRAINT FK_MED_VENTA_Cod_Medi REFERENCES MEDICAMENTOS(Cod_Medi),
    Info_Venta VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_MED_VENTA PRIMARY KEY (Cod_Medi)
);

-- Tabla MAYORISTA
CREATE TABLE MAYORISTA (

    Cod_Mayo NUMBER(3) PRIMARY KEY CONSTRAINT PK_MAYORISTA_Cod_Mayo,
    Nombre_Mayo VARCHAR2(30) NOT NULL
);

-- Tabla DISTRIBUCION
CREATE TABLE DISTRIBUCION (

    Cod_Mayo NUMBER(3) NOT NULL CONSTRAINT FK_DISTRIBUCION_Cod_Mayo REFERENCES MAYORISTA(Cod_Mayo),
    Cod_Medi NUMBER(3) NOT NULL CONSTRAINT FK_DISTRIBUCION_Cod_Medi REFERENCES MEDICAMENTOS(Cod_Medi),
    CONSTRAINT PK_DISTRIBUCION PRIMARY KEY (Cod_Mayo, Cod_Medi)
);

-- Tabla MED_INVES
CREATE TABLE MED_INVES (

    Cod_Medi NUMBER(3) NOT NULL CONSTRAINT FK_MED_INVES_Cod_Medi REFERENCES MEDICAMENTOS(Cod_Medi),
    Info_Inves VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_MED_INVES PRIMARY KEY (Cod_Medi)
);

-- Tabla REVISION
CREATE TABLE REVISION (

    Cod_Revi NUMBER(3) PRIMARY KEY CONSTRAINT PK_REVISION_Cod_Revi,
    Nombre_Revi VARCHAR2(20) NOT NULL
);

-- Tabla MED_REV
CREATE TABLE MED_REV (

    Cod_Medi NUMBER(3) NOT NULL CONSTRAINT FK_MED_REV_Cod_Medi REFERENCES MEDICAMENTOS(Cod_Medi),

    Cod_Revi NUMBER(3) NOT NULL CONSTRAINT FK_MED_REV_Cod_Revi REFERENCES REVISION(Cod_Revi),

    Fecha_Revi DATE NOT NULL,

    Valoracion_Revi NUMBER(2) NOT NULL,

   CONSTRAINT PK_MED_REV PRIMARY KEY (Cod_Medi, Cod_Revi, Fecha_Revi),
   CONSTRAINT CK_MED_REV_Fecha CHECK (Fecha_Revi > SYSDATE)
);



-- Not Null implícito en claves primarias y foráneas
-- Justificación: Las columnas que participan como claves primarias o foráneas ya tienen implícita la restricción NOT NULL según el estándar SQL.

4 -- Eliminación de restricción de rango en EMPLEADOS

ALTER TABLE EMPLEADOS DROP CONSTRAINT CK_EMPLEADOS_Comision;

5 -- Adición de restricción a Tipo_Medi en MEDICAMENTOS

ALTER TABLE MEDICAMENTOS ADD 
CONSTRAINT CK_MEDICAMENTOS_Tipo_Medi CHECK (LOWER(Tipo_Medi) IN ('investigacion', 'venta'));

6 -- Adición de valor por defecto a Tipo_Medi en MEDICAMENTOS

ALTER TABLE MEDICAMENTOS MODIFY Tipo_Medi DEFAULT 'venta';